### ISSUE TITLE
Mistake in Q-12

### ISSUE THREAD

**Issue by schuhmc** [pearcej/cpp4python#107]
Here's the link: https://runestone.academy/ns/books/published/cpp4python/IntroCpp/firstcppprogram.html#summary

The question reads "Q-12: True or False: Both Python and C++ support multi-line comments. In C++, they begin with /* and end with */."

According to the programmed answer, it is False because "Sorry, both languages do support multi-line comments, but they look different.", but the question doesn't imply that multi line comments in Python start with /* and end with */, it only states that "In C++, they begin with /* and end with */" which is true.

Proposed solution: Either change the wording of the question (e.g. remove "In C++,") or change the solution.

**Comment by opensdh** [comment]
More fundamentally, Python doesn't support multi-line comments at all, although (as the chapter mentions) triple-quoted strings are sometimes similar.
