### ISSUE TITLE
Typo in answer for Q-13

### ISSUE THREAD

**Issue by bryn-davis** [pearcej/cpp4python#112]
In [Section 1.6](https://runestone.academy/ns/books/published/cpp4python/IntroCpp/firstcppprogram.html#check-yourself), the answer for Q-13 states 

> The correct statement would be "cout << x;" or "std:cout x;" but the insertion operator is certainly needed.

The `<<` is missing from the second example. I.e., the answer should read

> The correct statement would be "cout << x;" or "std:cout << x;" but the insertion operator is certainly needed.

**Comment by pearcej** [comment]
Thanks!
