### ISSUE TITLE
cpp4py-v2 8.6 is 8.4 in the PreTeXt textbook

### ISSUE THREAD

**Issue by nathanwoohooyay** [pearcej/cpp4python#211]
8.6 is labeled as 8.4 in the PreTeXt textbook. A bunch of other chapters are also combined, which is resulting in the chapter numbers being different for different topics.

**Comment by kwizeras** [comment]
Putting 8.2 and 8.3 under 8.1. was an intentional structural decision from the author. 

=> issue #211 is no longer relevant!
