### ISSUE TITLE
2.5.1.1. Image and code not coordinated - confusing!

### ISSUE THREAD

**Issue by pearcej** [pearcej/cpp4python#40]
Figure Figure 2.3 has a 9 in varN. This is good.

However, the code snippets put a 100 into varN. This is confusing. Change the value of varN to 9 to better coordinate with image. (This needs to be changed in at least 2 places.)

**Comment by jawyoonis** [comment]
@jawyoonis working on this issue

**Comment by mupotsal** [comment]
@mupotsal I am working with Jamal on this.

**Comment by GioLomia** [comment]
@GioLomia fixed this issue
