### ISSUE TITLE
Pointer chapter activity 13 incorrect

### ISSUE THREAD

**Issue by pearcej** [pearcej/cpp4python#41]
Activity 13 in the pointer chapter is supposed to demonstrate a dangling pointer, but the pointer is not dangling.  This needs to be "fixed"... i.e. it needs to be broken.

**Comment by GioLomia** [comment]
@GioLomia working on this issue

**Comment by GioLomia** [comment]
Hi Dr. Jan, in the issue it says that the pointer is not dangling, is it because it refers to a 100 location in memory and sometimes there is something there?

**Comment by pearcej** [comment]
@GioLomia. Yes, the whole section makes no sense at this point. because ptrN is not a pointer.

You might break it with replacing lines 6 and 7 of activity 14 with:
    int varN = 9;
    int *ptrN;  

At the same time, you might fix the title of figure 5. It should NOT be FIXME2. It should describe memory, just be sure not to use spaces or special characters in the figure name.
