### ISSUE TITLE
Problem with cin in section 1.4.6

### ISSUE THREAD

**Issue by mario-nakazawa** [pearcej/cpp4python#83]
The interactive part for section 1.4.6, which refers to a replit sourced iframe, (looking at the HTML source) does not work when using incognito mode. It looks like this;
![image](https://user-images.githubusercontent.com/9629668/130262945-b39e6385-ec13-41ee-bbb1-93bbdf89cc87.png)

**Comment by pearcej** [comment]
Weird. it looks fine to me:
a
![image](https://user-images.githubusercontent.com/1608025/130448703-29c7f77e-401d-468a-9872-7ed0f3249d80.png)

I do think we should convert this to a self-contained cin solution, though.

**Comment by mario-nakazawa** [comment]
It could be because I am using Chrome in incognito mode. When I open the book with a regular Chrome window it works: fine.

**Comment by pearcej** [comment]
Ah, yes. That makes sense. I have updated your original comment to reflect that component of the issue.
